/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIActivityType.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

inline FString ToString(const APIActivityType::Values& Value)
{
	switch (Value)
	{
	case APIActivityType::Values::Mint:
		return TEXT("mint");
	case APIActivityType::Values::Burn:
		return TEXT("burn");
	case APIActivityType::Values::Transfer:
		return TEXT("transfer");
	case APIActivityType::Values::Sale:
		return TEXT("sale");
	case APIActivityType::Values::Deposit:
		return TEXT("deposit");
	case APIActivityType::Values::Withdrawal:
		return TEXT("withdrawal");
	}

	UE_LOG(LogImmutablezkEVMAPI, Error, TEXT("Invalid APIActivityType::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString APIActivityType::EnumToString(const APIActivityType::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, APIActivityType::Values& Value)
{
	static TMap<FString, APIActivityType::Values> StringToEnum = { 
		{ TEXT("mint"), APIActivityType::Values::Mint },
		{ TEXT("burn"), APIActivityType::Values::Burn },
		{ TEXT("transfer"), APIActivityType::Values::Transfer },
		{ TEXT("sale"), APIActivityType::Values::Sale },
		{ TEXT("deposit"), APIActivityType::Values::Deposit },
		{ TEXT("withdrawal"), APIActivityType::Values::Withdrawal }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool APIActivityType::EnumFromString(const FString& EnumAsString, APIActivityType::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const APIActivityType::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, APIActivityType::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void APIActivityType::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool APIActivityType::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
