/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIAssetVerificationStatus.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

inline FString ToString(const APIAssetVerificationStatus::Values& Value)
{
	switch (Value)
	{
	case APIAssetVerificationStatus::Values::Verified:
		return TEXT("verified");
	case APIAssetVerificationStatus::Values::Unverified:
		return TEXT("unverified");
	case APIAssetVerificationStatus::Values::Spam:
		return TEXT("spam");
	case APIAssetVerificationStatus::Values::Inactive:
		return TEXT("inactive");
	}

	UE_LOG(LogImmutablezkEVMAPI, Error, TEXT("Invalid APIAssetVerificationStatus::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString APIAssetVerificationStatus::EnumToString(const APIAssetVerificationStatus::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, APIAssetVerificationStatus::Values& Value)
{
	static TMap<FString, APIAssetVerificationStatus::Values> StringToEnum = { 
		{ TEXT("verified"), APIAssetVerificationStatus::Values::Verified },
		{ TEXT("unverified"), APIAssetVerificationStatus::Values::Unverified },
		{ TEXT("spam"), APIAssetVerificationStatus::Values::Spam },
		{ TEXT("inactive"), APIAssetVerificationStatus::Values::Inactive }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool APIAssetVerificationStatus::EnumFromString(const FString& EnumAsString, APIAssetVerificationStatus::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const APIAssetVerificationStatus::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, APIAssetVerificationStatus::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void APIAssetVerificationStatus::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool APIAssetVerificationStatus::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
