/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIBlockchainMetadata.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

void APIBlockchainMetadata::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("transaction_hash")); WriteJsonValue(Writer, TransactionHash);
	Writer->WriteIdentifierPrefix(TEXT("block_number")); WriteJsonValue(Writer, BlockNumber);
	Writer->WriteIdentifierPrefix(TEXT("transaction_index")); WriteJsonValue(Writer, TransactionIndex);
	if (LogIndex.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("log_index")); WriteJsonValue(Writer, LogIndex.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool APIBlockchainMetadata::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("transaction_hash"), TransactionHash);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("block_number"), BlockNumber);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("transaction_index"), TransactionIndex);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("log_index"), LogIndex);

	return ParseSuccess;
}

}
