/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APICall.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

void APICall::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("target_address")); WriteJsonValue(Writer, TargetAddress);
	Writer->WriteIdentifierPrefix(TEXT("function_signature")); WriteJsonValue(Writer, FunctionSignature);
	Writer->WriteIdentifierPrefix(TEXT("function_args")); WriteJsonValue(Writer, FunctionArgs);
	Writer->WriteObjectEnd();
}

bool APICall::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("target_address"), TargetAddress);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("function_signature"), FunctionSignature);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("function_args"), FunctionArgs);

	return ParseSuccess;
}

}
