/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIFulfillmentData200ResponseResult.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

void APIFulfillmentData200ResponseResult::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("fulfillable_orders")); WriteJsonValue(Writer, FulfillableOrders);
	Writer->WriteIdentifierPrefix(TEXT("unfulfillable_orders")); WriteJsonValue(Writer, UnfulfillableOrders);
	Writer->WriteObjectEnd();
}

bool APIFulfillmentData200ResponseResult::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("fulfillable_orders"), FulfillableOrders);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("unfulfillable_orders"), UnfulfillableOrders);

	return ParseSuccess;
}

}
