/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIMarketplaceContractType.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

inline FString ToString(const APIMarketplaceContractType::Values& Value)
{
	switch (Value)
	{
	case APIMarketplaceContractType::Values::ERC721:
		return TEXT("ERC721");
	case APIMarketplaceContractType::Values::ERC1155:
		return TEXT("ERC1155");
	}

	UE_LOG(LogImmutablezkEVMAPI, Error, TEXT("Invalid APIMarketplaceContractType::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString APIMarketplaceContractType::EnumToString(const APIMarketplaceContractType::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, APIMarketplaceContractType::Values& Value)
{
	static TMap<FString, APIMarketplaceContractType::Values> StringToEnum = { 
		{ TEXT("ERC721"), APIMarketplaceContractType::Values::ERC721 },
		{ TEXT("ERC1155"), APIMarketplaceContractType::Values::ERC1155 }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool APIMarketplaceContractType::EnumFromString(const FString& EnumAsString, APIMarketplaceContractType::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const APIMarketplaceContractType::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, APIMarketplaceContractType::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void APIMarketplaceContractType::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool APIMarketplaceContractType::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
