/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APISalePayment.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

void APISalePayment::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("token")); WriteJsonValue(Writer, Token);
	Writer->WriteIdentifierPrefix(TEXT("price_excluding_fees")); WriteJsonValue(Writer, PriceExcludingFees);
	Writer->WriteIdentifierPrefix(TEXT("price_including_fees")); WriteJsonValue(Writer, PriceIncludingFees);
	Writer->WriteIdentifierPrefix(TEXT("fees")); WriteJsonValue(Writer, Fees);
	Writer->WriteObjectEnd();
}

bool APISalePayment::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("token"), Token);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("price_excluding_fees"), PriceExcludingFees);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("price_including_fees"), PriceIncludingFees);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("fees"), Fees);

	return ParseSuccess;
}

}
