/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APITrade.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

void APITrade::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("buy")); WriteJsonValue(Writer, Buy);
	Writer->WriteIdentifierPrefix(TEXT("buyer_address")); WriteJsonValue(Writer, BuyerAddress);
	Writer->WriteIdentifierPrefix(TEXT("buyer_fees")); WriteJsonValue(Writer, BuyerFees);
	Writer->WriteIdentifierPrefix(TEXT("fees")); WriteJsonValue(Writer, Fees);
	Writer->WriteIdentifierPrefix(TEXT("chain")); WriteJsonValue(Writer, Chain);
	Writer->WriteIdentifierPrefix(TEXT("order_id")); WriteJsonValue(Writer, OrderId);
	if (BlockchainMetadata.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("blockchain_metadata")); WriteJsonValue(Writer, BlockchainMetadata.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("indexed_at")); WriteJsonValue(Writer, IndexedAt);
	Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, Id);
	Writer->WriteIdentifierPrefix(TEXT("sell")); WriteJsonValue(Writer, Sell);
	Writer->WriteIdentifierPrefix(TEXT("seller_address")); WriteJsonValue(Writer, SellerAddress);
	Writer->WriteIdentifierPrefix(TEXT("maker_address")); WriteJsonValue(Writer, MakerAddress);
	Writer->WriteIdentifierPrefix(TEXT("taker_address")); WriteJsonValue(Writer, TakerAddress);
	Writer->WriteObjectEnd();
}

bool APITrade::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("buy"), Buy);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("buyer_address"), BuyerAddress);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("buyer_fees"), BuyerFees);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("fees"), Fees);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("chain"), Chain);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("order_id"), OrderId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("blockchain_metadata"), BlockchainMetadata);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("indexed_at"), IndexedAt);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("id"), Id);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("sell"), Sell);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("seller_address"), SellerAddress);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("maker_address"), MakerAddress);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("taker_address"), TakerAddress);

	return ParseSuccess;
}

}
