/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIVerificationRequestStatus.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

inline FString ToString(const APIVerificationRequestStatus::Values& Value)
{
	switch (Value)
	{
	case APIVerificationRequestStatus::Values::Completed:
		return TEXT("completed");
	case APIVerificationRequestStatus::Values::Pending:
		return TEXT("pending");
	}

	UE_LOG(LogImmutablezkEVMAPI, Error, TEXT("Invalid APIVerificationRequestStatus::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString APIVerificationRequestStatus::EnumToString(const APIVerificationRequestStatus::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, APIVerificationRequestStatus::Values& Value)
{
	static TMap<FString, APIVerificationRequestStatus::Values> StringToEnum = { 
		{ TEXT("completed"), APIVerificationRequestStatus::Values::Completed },
		{ TEXT("pending"), APIVerificationRequestStatus::Values::Pending }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool APIVerificationRequestStatus::EnumFromString(const FString& EnumAsString, APIVerificationRequestStatus::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const APIVerificationRequestStatus::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, APIVerificationRequestStatus::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void APIVerificationRequestStatus::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool APIVerificationRequestStatus::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
