/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIActiveOrderStatus
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APIActiveOrderStatus : public Model
{
public:
    virtual ~APIActiveOrderStatus() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	enum class NameEnum
	{
		Active,
  	};

	static FString EnumToString(const NameEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, NameEnum& EnumValue);
	/* The order status that indicates an order can be fulfilled. */
	NameEnum Name;
};

}
