/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIActivityDetails.h"
#include "APIActivityType.h"
#include "APIBlockchainMetadata.h"
#include "APIChain.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIActivity
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APIActivity : public Model
{
public:
    virtual ~APIActivity() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Activity id in UUIDv4 format */
	FGuid Id;
	APIChain Chain;
	APIActivityType Type;
	APIActivityDetails Details;
	/* The time activity was updated at */
	FDateTime UpdatedAt;
	/* The time activity was indexed */
	FDateTime IndexedAt;
	TOptional<APIBlockchainMetadata> BlockchainMetadata;
};

}
