/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIBlockchainMetadata
 *
 * The metadata related to blockchain transaction
 */
class IMMUTABLEZKEVMAPI_API APIBlockchainMetadata : public Model
{
public:
    virtual ~APIBlockchainMetadata() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The transaction hash of the activity */
	FString TransactionHash;
	/* EVM block number (uint64 as string) */
	FString BlockNumber;
	/* Transaction index in a block (uint32 as string) */
	FString TransactionIndex;
	/* The log index of activity in a block (uint32 as string) */
	TOptional<FString> LogIndex;
};

}
