/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIOrder.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIFulfillableOrder
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APIFulfillableOrder : public Model
{
public:
    virtual ~APIFulfillableOrder() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	APIOrder Order;
	/* Token ID for the ERC721 or ERC1155 token when fulfilling a collection order */
	TOptional<FString> TokenId;
	FString ExtraData;
};

}
