/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIFillStatus
 *
 * The ratio of the order that has been filled, an order that has been fully filled will have the same numerator and denominator values.
 */
class IMMUTABLEZKEVMAPI_API APIFillStatus : public Model
{
public:
    virtual ~APIFillStatus() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The numerator of the fill status */
	FString Numerator;
	/* The denominator of the fill status */
	FString Denominator;
};

}
