/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APILastTrade.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIMarketNft
 *
 * NFT market data
 */
class IMMUTABLEZKEVMAPI_API APIMarketNft : public Model
{
public:
    virtual ~APIMarketNft() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<APILastTrade> LastTrade;
};

}
