/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIMarketPriceDetailsToken.h"
#include "APIMarketPriceFees.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIMarketPriceDetails
 *
 * Market Price details
 */
class IMMUTABLEZKEVMAPI_API APIMarketPriceDetails : public Model
{
public:
    virtual ~APIMarketPriceDetails() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	APIMarketPriceDetailsToken Token;
	/* The token amount value. This value is provided in the smallest unit of the token (e.g. wei for ETH) */
	FString Amount;
	/* The token amount value. This value is provided in the smallest unit of the token (e.g. wei for ETH) */
	FString FeeInclusiveAmount;
	TArray<APIMarketPriceFees> Fees;
	/* A mapping of converted prices for major currencies such as ETH, USD. All converted prices are fee-inclusive. */
	TOptional<TMap<FString, FString>> ConvertedPrices;
};

}
