/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIChain.h"
#include "APIOperatorAllowlistStatus.h"
#include "APIOperatorAllowlistStatusDetails.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIOperatorAllowlistContractStatus
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APIOperatorAllowlistContractStatus : public Model
{
public:
    virtual ~APIOperatorAllowlistContractStatus() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	APIChain Chain;
	/* The address of the contract */
	FString ContractAddress;
	APIOperatorAllowlistStatus Status;
	APIOperatorAllowlistStatusDetails Details;
	/* When the contract status was created */
	FDateTime CreatedAt;
	/* Who created the status */
	FString CreatedBy;
};

}
