/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIOrdersApi.h"

#include "APIAPIError400.h"
#include "APIAPIError401.h"
#include "APIAPIError404.h"
#include "APIAPIError429.h"
#include "APIAPIError500.h"
#include "APIAPIError501.h"
#include "APIBidResult.h"
#include "APICancelOrdersRequestBody.h"
#include "APICancelOrdersResult.h"
#include "APICollectionBidResult.h"
#include "APICreateBidRequestBody.h"
#include "APICreateCollectionBidRequestBody.h"
#include "APICreateListingRequestBody.h"
#include "APIFulfillmentData200Response.h"
#include "APIFulfillmentDataRequest.h"
#include "APIListBidsResult.h"
#include "APIListCollectionBidsResult.h"
#include "APIListListingsResult.h"
#include "APIListTradeResult.h"
#include "APIListingResult.h"
#include "APIOrderStatusName.h"
#include "APITradeResult.h"

namespace ImmutablezkEVMAPI
{

/* Cancel one or more orders
 *
 * Cancel one or more orders
*/
class IMMUTABLEZKEVMAPI_API APIOrdersApi::CancelOrdersRequest : public Request
{
public:
    virtual ~CancelOrdersRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString ChainName;
	APICancelOrdersRequestBody APICancelOrdersRequestBody;
};

class IMMUTABLEZKEVMAPI_API APIOrdersApi::CancelOrdersResponse : public Response
{
public:
    virtual ~CancelOrdersResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APICancelOrdersResult Content;
};

/* Create a bid
 *
 * Create a bid
*/
class IMMUTABLEZKEVMAPI_API APIOrdersApi::CreateBidRequest : public Request
{
public:
    virtual ~CreateBidRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString ChainName;
	APICreateBidRequestBody APICreateBidRequestBody;
};

class IMMUTABLEZKEVMAPI_API APIOrdersApi::CreateBidResponse : public Response
{
public:
    virtual ~CreateBidResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIBidResult Content;
};

/* Create a collection bid
 *
 * Create a collection bid
*/
class IMMUTABLEZKEVMAPI_API APIOrdersApi::CreateCollectionBidRequest : public Request
{
public:
    virtual ~CreateCollectionBidRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString ChainName;
	APICreateCollectionBidRequestBody APICreateCollectionBidRequestBody;
};

class IMMUTABLEZKEVMAPI_API APIOrdersApi::CreateCollectionBidResponse : public Response
{
public:
    virtual ~CreateCollectionBidResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APICollectionBidResult Content;
};

/* Create a listing
 *
 * Create a listing
*/
class IMMUTABLEZKEVMAPI_API APIOrdersApi::CreateListingRequest : public Request
{
public:
    virtual ~CreateListingRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString ChainName;
	APICreateListingRequestBody APICreateListingRequestBody;
};

class IMMUTABLEZKEVMAPI_API APIOrdersApi::CreateListingResponse : public Response
{
public:
    virtual ~CreateListingResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIListingResult Content;
};

/* Retrieve fulfillment data for orders
 *
 * Retrieve signed fulfillment data based on the list of order IDs and corresponding fees.
*/
class IMMUTABLEZKEVMAPI_API APIOrdersApi::FulfillmentDataRequest : public Request
{
public:
    virtual ~FulfillmentDataRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString ChainName;
	TArray<APIFulfillmentDataRequest> APIFulfillmentDataRequest;
};

class IMMUTABLEZKEVMAPI_API APIOrdersApi::FulfillmentDataResponse : public Response
{
public:
    virtual ~FulfillmentDataResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIFulfillmentData200Response Content;
};

/* Get a single bid by ID
 *
 * Get a single bid by ID
*/
class IMMUTABLEZKEVMAPI_API APIOrdersApi::GetBidRequest : public Request
{
public:
    virtual ~GetBidRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString ChainName;
	/* Global Bid identifier */
	FGuid BidId;
};

class IMMUTABLEZKEVMAPI_API APIOrdersApi::GetBidResponse : public Response
{
public:
    virtual ~GetBidResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIBidResult Content;
};

/* Get a single collection bid by ID
 *
 * Get a single collection bid by ID
*/
class IMMUTABLEZKEVMAPI_API APIOrdersApi::GetCollectionBidRequest : public Request
{
public:
    virtual ~GetCollectionBidRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString ChainName;
	/* Global Collection Bid identifier */
	FGuid CollectionBidId;
};

class IMMUTABLEZKEVMAPI_API APIOrdersApi::GetCollectionBidResponse : public Response
{
public:
    virtual ~GetCollectionBidResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APICollectionBidResult Content;
};

/* Get a single listing by ID
 *
 * Get a single listing by ID
*/
class IMMUTABLEZKEVMAPI_API APIOrdersApi::GetListingRequest : public Request
{
public:
    virtual ~GetListingRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString ChainName;
	/* Global Order identifier */
	FGuid ListingId;
};

class IMMUTABLEZKEVMAPI_API APIOrdersApi::GetListingResponse : public Response
{
public:
    virtual ~GetListingResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIListingResult Content;
};

/* Get a single trade by ID
 *
 * Get a single trade by ID
*/
class IMMUTABLEZKEVMAPI_API APIOrdersApi::GetTradeRequest : public Request
{
public:
    virtual ~GetTradeRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString ChainName;
	/* Global Trade identifier */
	FGuid TradeId;
};

class IMMUTABLEZKEVMAPI_API APIOrdersApi::GetTradeResponse : public Response
{
public:
    virtual ~GetTradeResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APITradeResult Content;
};

/* List all bids
 *
 * List all bids
*/
class IMMUTABLEZKEVMAPI_API APIOrdersApi::ListBidsRequest : public Request
{
public:
    virtual ~ListBidsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString ChainName;
	/* Order status to filter by */
	TOptional<APIOrderStatusName> Status;
	/* Buy item contract address to filter by */
	TOptional<FString> BuyItemContractAddress;
	/* Sell item contract address to filter by */
	TOptional<FString> SellItemContractAddress;
	/* The account address of the user who created the bid */
	TOptional<FString> AccountAddress;
	/* The metadata_id of the buy item */
	TOptional<FGuid> BuyItemMetadataId;
	/* buy item token identifier to filter by */
	TOptional<FString> BuyItemTokenId;
	/* From updated at including given date */
	TOptional<FDateTime> FromUpdatedAt;
	/* Maximum number of orders to return per page */
	TOptional<int32> PageSize;
	enum class SortByEnum
	{
		CreatedAt,
		UpdatedAt,
		SellItemAmount,
  	};

	static FString EnumToString(const SortByEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, SortByEnum& EnumValue);
	/* Order field to sort by. `sell_item_amount` sorts by per token price, for example if 10eth is offered for 5 ERC1155 items, it’s sorted as 2eth for `sell_item_amount`. */
	TOptional<SortByEnum> SortBy;
	enum class SortDirectionEnum
	{
		Asc,
		Desc,
  	};

	static FString EnumToString(const SortDirectionEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, SortDirectionEnum& EnumValue);
	/* Ascending or descending direction for sort */
	TOptional<SortDirectionEnum> SortDirection;
	/* Page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
};

class IMMUTABLEZKEVMAPI_API APIOrdersApi::ListBidsResponse : public Response
{
public:
    virtual ~ListBidsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIListBidsResult Content;
};

/* List all collection bids
 *
 * List all collection bids
*/
class IMMUTABLEZKEVMAPI_API APIOrdersApi::ListCollectionBidsRequest : public Request
{
public:
    virtual ~ListCollectionBidsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString ChainName;
	/* Order status to filter by */
	TOptional<APIOrderStatusName> Status;
	/* Buy item contract address to filter by */
	TOptional<FString> BuyItemContractAddress;
	/* Sell item contract address to filter by */
	TOptional<FString> SellItemContractAddress;
	/* The account address of the user who created the bid */
	TOptional<FString> AccountAddress;
	/* From updated at including given date */
	TOptional<FDateTime> FromUpdatedAt;
	/* Maximum number of orders to return per page */
	TOptional<int32> PageSize;
	enum class SortByEnum
	{
		CreatedAt,
		UpdatedAt,
		SellItemAmount,
  	};

	static FString EnumToString(const SortByEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, SortByEnum& EnumValue);
	/* Order field to sort by. `sell_item_amount` sorts by per token price, for example if 10eth is offered for 5 ERC1155 items, it’s sorted as 2eth for `sell_item_amount`. */
	TOptional<SortByEnum> SortBy;
	enum class SortDirectionEnum
	{
		Asc,
		Desc,
  	};

	static FString EnumToString(const SortDirectionEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, SortDirectionEnum& EnumValue);
	/* Ascending or descending direction for sort */
	TOptional<SortDirectionEnum> SortDirection;
	/* Page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
};

class IMMUTABLEZKEVMAPI_API APIOrdersApi::ListCollectionBidsResponse : public Response
{
public:
    virtual ~ListCollectionBidsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIListCollectionBidsResult Content;
};

/* List all listings
 *
 * List all listings
*/
class IMMUTABLEZKEVMAPI_API APIOrdersApi::ListListingsRequest : public Request
{
public:
    virtual ~ListListingsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString ChainName;
	/* Order status to filter by */
	TOptional<APIOrderStatusName> Status;
	/* Sell item contract address to filter by */
	TOptional<FString> SellItemContractAddress;
	enum class BuyItemTypeEnum
	{
		Native,
		ERC20,
  	};

	static FString EnumToString(const BuyItemTypeEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, BuyItemTypeEnum& EnumValue);
	/* Buy item type to filter by */
	TOptional<BuyItemTypeEnum> BuyItemType;
	/* Buy item contract address to filter by */
	TOptional<FString> BuyItemContractAddress;
	/* The account address of the user who created the listing */
	TOptional<FString> AccountAddress;
	/* The metadata_id of the sell item */
	TOptional<FGuid> SellItemMetadataId;
	/* Sell item token identifier to filter by */
	TOptional<FString> SellItemTokenId;
	/* From updated at including given date */
	TOptional<FDateTime> FromUpdatedAt;
	/* Maximum number of orders to return per page */
	TOptional<int32> PageSize;
	enum class SortByEnum
	{
		CreatedAt,
		UpdatedAt,
		BuyItemAmount,
  	};

	static FString EnumToString(const SortByEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, SortByEnum& EnumValue);
	/* Order field to sort by. `buy_item_amount` sorts by per token price, for example if 5 ERC-1155s are on sale for 10eth, it’s sorted as 2eth for `buy_item_amount`. */
	TOptional<SortByEnum> SortBy;
	enum class SortDirectionEnum
	{
		Asc,
		Desc,
  	};

	static FString EnumToString(const SortDirectionEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, SortDirectionEnum& EnumValue);
	/* Ascending or descending direction for sort */
	TOptional<SortDirectionEnum> SortDirection;
	/* Page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
};

class IMMUTABLEZKEVMAPI_API APIOrdersApi::ListListingsResponse : public Response
{
public:
    virtual ~ListListingsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIListListingsResult Content;
};

/* List all trades
 *
 * List all trades
*/
class IMMUTABLEZKEVMAPI_API APIOrdersApi::ListTradesRequest : public Request
{
public:
    virtual ~ListTradesRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	FString ChainName;
	TOptional<FString> AccountAddress;
	TOptional<FString> SellItemContractAddress;
	/* From indexed at including given date */
	TOptional<FDateTime> FromIndexedAt;
	/* Maximum number of trades to return per page */
	TOptional<int32> PageSize;
	enum class SortByEnum
	{
		IndexedAt,
  	};

	static FString EnumToString(const SortByEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, SortByEnum& EnumValue);
	/* Trade field to sort by */
	TOptional<SortByEnum> SortBy;
	enum class SortDirectionEnum
	{
		Asc,
		Desc,
  	};

	static FString EnumToString(const SortDirectionEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, SortDirectionEnum& EnumValue);
	/* Ascending or descending direction for sort */
	TOptional<SortDirectionEnum> SortDirection;
	/* Page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
};

class IMMUTABLEZKEVMAPI_API APIOrdersApi::ListTradesResponse : public Response
{
public:
    virtual ~ListTradesResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIListTradeResult Content;
};

}
