/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIActiveOrderStatus.h"
#include "APICancelledOrderStatus.h"
#include "APIExpiredOrderStatus.h"
#include "APIFilledOrderStatus.h"
#include "APIInactiveOrderStatus.h"
#include "APIPendingOrderStatus.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIOrderStatus
 *
 * The Order status
 */
class IMMUTABLEZKEVMAPI_API APIOrderStatus : public Model
{
public:
    virtual ~APIOrderStatus() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	enum class NameEnum
	{
		Expired,
  	};

	static FString EnumToString(const NameEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, NameEnum& EnumValue);
	/* A terminal order status indicating that an order cannot be fulfilled due to expiry. */
	NameEnum Name;
	/* Whether the cancellation of the order is pending */
	bool Pending = false;
	enum class CancellationTypeEnum
	{
		OnChain,
		OffChain,
		Underfunded,
  	};

	static FString EnumToString(const CancellationTypeEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, CancellationTypeEnum& EnumValue);
	/* Whether the cancellation was done on-chain or off-chain or as a result of an underfunded account */
	CancellationTypeEnum CancellationType;
	/* Whether the order has been evaluated after its creation */
	bool Evaluated = false;
	/* Whether the order has reached its specified start time */
	bool Started = false;
	/* Whether the order offerer has sufficient approvals */
	bool SufficientApprovals = false;
	/* Whether the order offerer still has sufficient balance to complete the order */
	bool SufficientBalances = false;
};

}
