/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIPendingOrderStatus
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APIPendingOrderStatus : public Model
{
public:
    virtual ~APIPendingOrderStatus() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	enum class NameEnum
	{
		Pending,
  	};

	static FString EnumToString(const NameEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, NameEnum& EnumValue);
	/* The order status that indicates the order is yet to be active due to various reasons. */
	NameEnum Name;
	/* Whether the order has been evaluated after its creation */
	bool Evaluated = false;
	/* Whether the order has reached its specified start time */
	bool Started = false;
};

}
