/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APINFTQuoteResult.h"
#include "APIPage.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIQuotesForNFTsResult
 *
 * Quotes for NFTs result
 */
class IMMUTABLEZKEVMAPI_API APIQuotesForNFTsResult : public Model
{
public:
    virtual ~APIQuotesForNFTsResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* List of quotes */
	TArray<APINFTQuoteResult> Result;
	APIPage Page;
};

}
