/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"

namespace ImmutablezkEVMAPI
{

/*
 * APISignCraftingRequestMultiCaller
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APISignCraftingRequestMultiCaller : public Model
{
public:
    virtual ~APISignCraftingRequestMultiCaller() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* An Ethereum address */
	FString Address;
	/* The name of the multicaller contract */
	FString Name;
	/* The version of the multicaller contract */
	FString Version;
};

}
