/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIChain.h"
#include "APIMarketplaceContractType.h"
#include "APINFTMetadataAttribute.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIStack
 *
 * Stack
 */
class IMMUTABLEZKEVMAPI_API APIStack : public Model
{
public:
    virtual ~APIStack() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Stack ID */
	FGuid StackId;
	APIChain Chain;
	/* Contract address */
	FString ContractAddress;
	APIMarketplaceContractType ContractType;
	/* When the metadata was created */
	FDateTime CreatedAt;
	/* When the metadata was last updated */
	FDateTime UpdatedAt;
	/* The name of the NFT */
	TOptional<FString> Name;
	/* The description of the NFT */
	TOptional<FString> Description;
	/* The image url of the NFT */
	TOptional<FString> Image;
	/* The external website link of NFT */
	TOptional<FString> ExternalUrl;
	/* The animation url of the NFT */
	TOptional<FString> AnimationUrl;
	/* The youtube URL of NFT */
	TOptional<FString> YoutubeUrl;
	/* List of Metadata attributes */
	TOptional<TArray<APINFTMetadataAttribute>> Attributes;
};

}
