/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APISaleFee.h"
#include "APISalePaymentToken.h"

namespace ImmutablezkEVMAPI
{

/*
 * APISalePayment
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APISalePayment : public Model
{
public:
    virtual ~APISalePayment() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	APISalePaymentToken Token;
	/* The base price of the sale not including any fees */
	FString PriceExcludingFees;
	/* The total price of the sale. Includes the sum of all fees */
	FString PriceIncludingFees;
	/* The fees associated with this sale */
	TArray<APISaleFee> Fees;
};

}
