/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIUserInfo
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APIUserInfo : public Model
{
public:
    virtual ~APIUserInfo() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* The user's id */
	FString Sub;
	/* The user's email address */
	TOptional<FString> Email;
	/* The user's Passport address if it has been registered */
	TOptional<FString> PassportAddress;
	/* The user's list of linked addresses */
	TArray<FString> LinkedAddresses;
};

}
