/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APICancelledOrderStatusCancellationType.h"

#include "ImmutableOrderbookModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOrderbook
{

inline FString ToString(const APICancelledOrderStatusCancellationType::Values& Value)
{
	switch (Value)
	{
	case APICancelledOrderStatusCancellationType::Values::OnChain:
		return TEXT("ON_CHAIN");
	case APICancelledOrderStatusCancellationType::Values::OffChain:
		return TEXT("OFF_CHAIN");
	case APICancelledOrderStatusCancellationType::Values::Underfunded:
		return TEXT("UNDERFUNDED");
	}

	UE_LOG(LogImmutableOrderbook, Error, TEXT("Invalid APICancelledOrderStatusCancellationType::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString APICancelledOrderStatusCancellationType::EnumToString(const APICancelledOrderStatusCancellationType::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, APICancelledOrderStatusCancellationType::Values& Value)
{
	static TMap<FString, APICancelledOrderStatusCancellationType::Values> StringToEnum = { 
		{ TEXT("ON_CHAIN"), APICancelledOrderStatusCancellationType::Values::OnChain },
		{ TEXT("OFF_CHAIN"), APICancelledOrderStatusCancellationType::Values::OffChain },
		{ TEXT("UNDERFUNDED"), APICancelledOrderStatusCancellationType::Values::Underfunded }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool APICancelledOrderStatusCancellationType::EnumFromString(const FString& EnumAsString, APICancelledOrderStatusCancellationType::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const APICancelledOrderStatusCancellationType::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, APICancelledOrderStatusCancellationType::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void APICancelledOrderStatusCancellationType::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool APICancelledOrderStatusCancellationType::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
