/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIItemType.h"

#include "ImmutableOrderbookModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOrderbook
{
// -- DIVERGE
void APIItemType::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteValue(Value);
}

bool APIItemType::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return JsonValue->TryGetNumber(Value);
}
// -- DIVERGE
}
