/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIOrderFillStatus.h"

#include "ImmutableOrderbookModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOrderbook
{

void APIOrderFillStatus::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Denominator.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("denominator")); WriteJsonValue(Writer, Denominator.GetValue());
	}
	if (Numerator.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("numerator")); WriteJsonValue(Writer, Numerator.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool APIOrderFillStatus::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("denominator"), Denominator);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("numerator"), Numerator);

	return ParseSuccess;
}

}
