/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIPrepareListing200Response.h"

#include "ImmutableOrderbookModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOrderbook
{

void APIPrepareListing200Response::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("actions")); WriteJsonValue(Writer, Actions);
	Writer->WriteIdentifierPrefix(TEXT("orderComponents")); WriteJsonValue(Writer, OrderComponents);
	Writer->WriteIdentifierPrefix(TEXT("orderHash")); WriteJsonValue(Writer, OrderHash);
	Writer->WriteObjectEnd();
}

bool APIPrepareListing200Response::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("actions"), Actions);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("orderComponents"), OrderComponents);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("orderHash"), OrderHash);

	return ParseSuccess;
}

}
