/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APITransactionPurpose.h"

#include "ImmutableOrderbookModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutableOrderbook
{

inline FString ToString(const APITransactionPurpose::Values& Value)
{
	switch (Value)
	{
	case APITransactionPurpose::Values::Approval:
		return TEXT("APPROVAL");
	case APITransactionPurpose::Values::FulfillOrder:
		return TEXT("FULFILL_ORDER");
	case APITransactionPurpose::Values::Cancel:
		return TEXT("CANCEL");
	}

	UE_LOG(LogImmutableOrderbook, Error, TEXT("Invalid APITransactionPurpose::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString APITransactionPurpose::EnumToString(const APITransactionPurpose::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, APITransactionPurpose::Values& Value)
{
	static TMap<FString, APITransactionPurpose::Values> StringToEnum = { 
		{ TEXT("APPROVAL"), APITransactionPurpose::Values::Approval },
		{ TEXT("FULFILL_ORDER"), APITransactionPurpose::Values::FulfillOrder },
		{ TEXT("CANCEL"), APITransactionPurpose::Values::Cancel }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool APITransactionPurpose::EnumFromString(const FString& EnumAsString, APITransactionPurpose::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const APITransactionPurpose::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, APITransactionPurpose::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void APITransactionPurpose::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool APITransactionPurpose::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
