/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIActivityAsset.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

void APIActivityAsset::WriteJson(JsonWriter& Writer) const
{
	if (const APIActivityNFT* APIActivityNFTValue = OneOf.TryGet<APIActivityNFT>())
	{
		WriteJsonValue(Writer, *APIActivityNFTValue);
	}
	else if (const APIActivityToken* APIActivityTokenValue = OneOf.TryGet<APIActivityToken>())
	{
		WriteJsonValue(Writer, *APIActivityTokenValue);
	}
}

bool APIActivityAsset::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	APIActivityNFT APIActivityNFTValue;
	if (const bool bIsAPIActivityNFT = TryGetJsonValue(JsonValue, APIActivityNFTValue))
	{
		OneOf.Set<APIActivityNFT>(APIActivityNFTValue);
		return true;
	}

	APIActivityToken APIActivityTokenValue;
	if (const bool bIsAPIActivityToken = TryGetJsonValue(JsonValue, APIActivityTokenValue))
	{
		OneOf.Set<APIActivityToken>(APIActivityTokenValue);
		return true;
	}

	return false;
}

}
