/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIMarket.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

void APIMarket::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (FloorListing.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("floor_listing")); WriteJsonValue(Writer, FloorListing.GetValue());
	}
	if (TopBid.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("top_bid")); WriteJsonValue(Writer, TopBid.GetValue());
	}
	if (LastTrade.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("last_trade")); WriteJsonValue(Writer, LastTrade.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool APIMarket::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("floor_listing"), FloorListing);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("top_bid"), TopBid);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("last_trade"), LastTrade);

	return ParseSuccess;
}

}
