/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIOperatorAllowlistStatusDetails.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

void APIOperatorAllowlistStatusDetails::WriteJson(JsonWriter& Writer) const
{
	if (const APIOperatorAllowlistStatusRequested* APIOperatorAllowlistStatusRequestedValue = OneOf.TryGet<APIOperatorAllowlistStatusRequested>())
	{
		WriteJsonValue(Writer, *APIOperatorAllowlistStatusRequestedValue);
	}
	else if (const APIOperatorAllowlistStatusUpdated* APIOperatorAllowlistStatusUpdatedValue = OneOf.TryGet<APIOperatorAllowlistStatusUpdated>())
	{
		WriteJsonValue(Writer, *APIOperatorAllowlistStatusUpdatedValue);
	}
}

bool APIOperatorAllowlistStatusDetails::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	APIOperatorAllowlistStatusRequested APIOperatorAllowlistStatusRequestedValue;
	if (const bool bIsAPIOperatorAllowlistStatusRequested = TryGetJsonValue(JsonValue, APIOperatorAllowlistStatusRequestedValue))
	{
		OneOf.Set<APIOperatorAllowlistStatusRequested>(APIOperatorAllowlistStatusRequestedValue);
		return true;
	}

	APIOperatorAllowlistStatusUpdated APIOperatorAllowlistStatusUpdatedValue;
	if (const bool bIsAPIOperatorAllowlistStatusUpdated = TryGetJsonValue(JsonValue, APIOperatorAllowlistStatusUpdatedValue))
	{
		OneOf.Set<APIOperatorAllowlistStatusUpdated>(APIOperatorAllowlistStatusUpdatedValue);
		return true;
	}

	return false;
}

}
