/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIOrderStatus.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

inline FString ToString(const APIOrderStatus::NameEnum& Value)
{
	switch (Value)
	{
	case APIOrderStatus::NameEnum::Expired:
		return TEXT("EXPIRED");
	}

	UE_LOG(LogImmutablezkEVMAPI, Error, TEXT("Invalid APIOrderStatus::NameEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString APIOrderStatus::EnumToString(const APIOrderStatus::NameEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, APIOrderStatus::NameEnum& Value)
{
	static TMap<FString, APIOrderStatus::NameEnum> StringToEnum = { 
		{ TEXT("EXPIRED"), APIOrderStatus::NameEnum::Expired }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool APIOrderStatus::EnumFromString(const FString& EnumAsString, APIOrderStatus::NameEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const APIOrderStatus::NameEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, APIOrderStatus::NameEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

inline FString ToString(const APIOrderStatus::CancellationTypeEnum& Value)
{
	switch (Value)
	{
	case APIOrderStatus::CancellationTypeEnum::OnChain:
		return TEXT("ON_CHAIN");
	case APIOrderStatus::CancellationTypeEnum::OffChain:
		return TEXT("OFF_CHAIN");
	case APIOrderStatus::CancellationTypeEnum::Underfunded:
		return TEXT("UNDERFUNDED");
	}

	UE_LOG(LogImmutablezkEVMAPI, Error, TEXT("Invalid APIOrderStatus::CancellationTypeEnum Value (%d)"), (int)Value);
	return TEXT("");
}

FString APIOrderStatus::EnumToString(const APIOrderStatus::CancellationTypeEnum& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, APIOrderStatus::CancellationTypeEnum& Value)
{
	static TMap<FString, APIOrderStatus::CancellationTypeEnum> StringToEnum = { 
		{ TEXT("ON_CHAIN"), APIOrderStatus::CancellationTypeEnum::OnChain },
		{ TEXT("OFF_CHAIN"), APIOrderStatus::CancellationTypeEnum::OffChain },
		{ TEXT("UNDERFUNDED"), APIOrderStatus::CancellationTypeEnum::Underfunded }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool APIOrderStatus::EnumFromString(const FString& EnumAsString, APIOrderStatus::CancellationTypeEnum& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const APIOrderStatus::CancellationTypeEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, APIOrderStatus::CancellationTypeEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void APIOrderStatus::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name);
	Writer->WriteIdentifierPrefix(TEXT("pending")); WriteJsonValue(Writer, Pending);
	Writer->WriteIdentifierPrefix(TEXT("cancellation_type")); WriteJsonValue(Writer, CancellationType);
	Writer->WriteIdentifierPrefix(TEXT("evaluated")); WriteJsonValue(Writer, Evaluated);
	Writer->WriteIdentifierPrefix(TEXT("started")); WriteJsonValue(Writer, Started);
	Writer->WriteIdentifierPrefix(TEXT("sufficient_approvals")); WriteJsonValue(Writer, SufficientApprovals);
	Writer->WriteIdentifierPrefix(TEXT("sufficient_balances")); WriteJsonValue(Writer, SufficientBalances);
	Writer->WriteObjectEnd();
}

bool APIOrderStatus::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("pending"), Pending);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("cancellation_type"), CancellationType);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("evaluated"), Evaluated);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("started"), Started);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("sufficient_approvals"), SufficientApprovals);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("sufficient_balances"), SufficientBalances);

	return ParseSuccess;
}

}
