/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APIOrganisationTier.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

inline FString ToString(const APIOrganisationTier::Values& Value)
{
	switch (Value)
	{
	case APIOrganisationTier::Values::Common:
		return TEXT("common");
	case APIOrganisationTier::Values::Uncommon:
		return TEXT("uncommon");
	case APIOrganisationTier::Values::Rare:
		return TEXT("rare");
	case APIOrganisationTier::Values::Epic:
		return TEXT("epic");
	case APIOrganisationTier::Values::Legendary:
		return TEXT("legendary");
	}

	UE_LOG(LogImmutablezkEVMAPI, Error, TEXT("Invalid APIOrganisationTier::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString APIOrganisationTier::EnumToString(const APIOrganisationTier::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, APIOrganisationTier::Values& Value)
{
	static TMap<FString, APIOrganisationTier::Values> StringToEnum = { 
		{ TEXT("common"), APIOrganisationTier::Values::Common },
		{ TEXT("uncommon"), APIOrganisationTier::Values::Uncommon },
		{ TEXT("rare"), APIOrganisationTier::Values::Rare },
		{ TEXT("epic"), APIOrganisationTier::Values::Epic },
		{ TEXT("legendary"), APIOrganisationTier::Values::Legendary }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool APIOrganisationTier::EnumFromString(const FString& EnumAsString, APIOrganisationTier::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const APIOrganisationTier::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, APIOrganisationTier::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void APIOrganisationTier::WriteJson(JsonWriter& Writer) const
{
	WriteJsonValue(Writer, Value);
}

bool APIOrganisationTier::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Value);
}

}
