/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "APISalePaymentToken.h"

#include "ImmutablezkEVMAPIModule.h"
#include "APIHelpers.h"

#include "Templates/SharedPointer.h"

namespace ImmutablezkEVMAPI
{

void APISalePaymentToken::WriteJson(JsonWriter& Writer) const
{
	if (const APIActivityNativeToken* APIActivityNativeTokenValue = OneOf.TryGet<APIActivityNativeToken>())
	{
		WriteJsonValue(Writer, *APIActivityNativeTokenValue);
	}
	else if (const APIActivityToken* APIActivityTokenValue = OneOf.TryGet<APIActivityToken>())
	{
		WriteJsonValue(Writer, *APIActivityTokenValue);
	}
}

bool APISalePaymentToken::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	APIActivityNativeToken APIActivityNativeTokenValue;
	if (const bool bIsAPIActivityNativeToken = TryGetJsonValue(JsonValue, APIActivityNativeTokenValue))
	{
		OneOf.Set<APIActivityNativeToken>(APIActivityNativeTokenValue);
		return true;
	}

	APIActivityToken APIActivityTokenValue;
	if (const bool bIsAPIActivityToken = TryGetJsonValue(JsonValue, APIActivityTokenValue))
	{
		OneOf.Set<APIActivityToken>(APIActivityTokenValue);
		return true;
	}

	return false;
}

}
