/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIFeeValue.h"
#include "APIOrderComponents.h"

namespace ImmutableOrderbook
{

/*
 * APICreateListingRequest
 *
 * 
 */
class IMMUTABLEORDERBOOK_API APICreateListingRequest : public Model
{
public:
    virtual ~APICreateListingRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TArray<APIFeeValue> MakerFees;
	APIOrderComponents OrderComponents;
	FString OrderHash;
	FString OrderSignature;
};

}
