/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"

namespace ImmutableOrderbook
{

/*
 * APICancelOrders200ResponseResultFailedCancellationsInner
 *
 * 
 */
class IMMUTABLEORDERBOOK_API APICancelOrders200ResponseResultFailedCancellationsInner : public Model
{
public:
    virtual ~APICancelOrders200ResponseResultFailedCancellationsInner() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* ID of the order which failed to be cancelled */
	TOptional<FString> Order;
	enum class ReasonCodeEnum
	{
		Filled,
  	};

	static FString EnumToString(const ReasonCodeEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, ReasonCodeEnum& EnumValue);
	/* Reason code indicating why the order failed to be cancelled */
	TOptional<ReasonCodeEnum> ReasonCode;
};

}
