/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIFulfillOrderRequestTakerFeesInner.h"

namespace ImmutableOrderbook
{

/*
 * APIFulfillOrderRequest
 *
 * 
 */
class IMMUTABLEORDERBOOK_API APIFulfillOrderRequest : public Model
{
public:
    virtual ~APIFulfillOrderRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* listingId */
	FString ListingId;
	/* takerAddress */
	FString TakerAddress;
	/* takerFees */
	TArray<APIFulfillOrderRequestTakerFeesInner> TakerFees;
	/* amountToFill */
	TOptional<FString> AmountToFill;
};

}
