/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIOrderComponentsConsiderationInner.h"
#include "APIOrderComponentsOfferInner.h"
#include "APIOrderType.h"

namespace ImmutableOrderbook
{

/*
 * APIOrderComponents
 *
 * 
 */
class IMMUTABLEORDERBOOK_API APIOrderComponents : public Model
{
public:
    virtual ~APIOrderComponents() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString ConduitKey;
	TArray<APIOrderComponentsConsiderationInner> Consideration;
	FString EndTime;
	TArray<APIOrderComponentsOfferInner> Offer;
	FString Offerer;
	APIOrderType OrderType;
	FString Salt;
	FString StartTime;
	FString TotalOriginalConsiderationItems;
	FString Zone;
	FString ZoneHash;
	FString Counter;
};

}
