/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APISignableAction.h"

namespace ImmutableOrderbook
{

/*
 * APIPrepareOrderCancellations200Response
 *
 * Response schema for the prepareOrderCancellations endpoint
 */
class IMMUTABLEORDERBOOK_API APIPrepareOrderCancellations200Response : public Model
{
public:
    virtual ~APIPrepareOrderCancellations200Response() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<APISignableAction> SignableAction;
};

}
