/**
 * TS SDK API
 * running ts sdk as an api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APITransactionActionPopulatedTransactions.h"
#include "APITransactionPurpose.h"

namespace ImmutableOrderbook
{

/*
 * APITransactionAction
 *
 * 
 */
class IMMUTABLEORDERBOOK_API APITransactionAction : public Model
{
public:
    virtual ~APITransactionAction() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<APITransactionActionPopulatedTransactions> PopulatedTransactions;
	TOptional<APITransactionPurpose> Purpose;
	enum class TypeEnum
	{
		Transaction,
  	};

	static FString EnumToString(const TypeEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, TypeEnum& EnumValue);
	TypeEnum Type;
};

}
