/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "APIBaseModel.h"

namespace ImmutablezkEVMAPI
{

class IMMUTABLEZKEVMAPI_API APIActivitiesApi
{
public:
	APIActivitiesApi();
	~APIActivitiesApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class GetActivityRequest;
	class GetActivityResponse;
	class ListActivitiesRequest;
	class ListActivitiesResponse;
	class ListActivityHistoryRequest;
	class ListActivityHistoryResponse;
	
    DECLARE_DELEGATE_OneParam(FGetActivityDelegate, const GetActivityResponse&);
    DECLARE_DELEGATE_OneParam(FListActivitiesDelegate, const ListActivitiesResponse&);
    DECLARE_DELEGATE_OneParam(FListActivityHistoryDelegate, const ListActivityHistoryResponse&);
    
    FHttpRequestPtr GetActivity(const GetActivityRequest& Request, const FGetActivityDelegate& Delegate = FGetActivityDelegate()) const;
    FHttpRequestPtr ListActivities(const ListActivitiesRequest& Request, const FListActivitiesDelegate& Delegate = FListActivitiesDelegate()) const;
    FHttpRequestPtr ListActivityHistory(const ListActivityHistoryRequest& Request, const FListActivityHistoryDelegate& Delegate = FListActivityHistoryDelegate()) const;
    
private:
    void OnGetActivityResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetActivityDelegate Delegate) const;
    void OnListActivitiesResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FListActivitiesDelegate Delegate) const;
    void OnListActivityHistoryResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FListActivityHistoryDelegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
