/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "Misc/TVariant.h"

#include "APIBaseModel.h"
#include "APIActivityNFT.h"
#include "APIActivityToken.h"
#include "APITokenContractType.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIActivityAsset
 *
 * The contract and asset details for this activity
 */
class IMMUTABLEZKEVMAPI_API APIActivityAsset : public Model
{
public:
    virtual ~APIActivityAsset() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TVariant<APIActivityNFT, APIActivityToken> OneOf;
};

}
