/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIActivitiesApi.h"

#include "APIAPIError400.h"
#include "APIAPIError404.h"
#include "APIAPIError500.h"
#include "APIActivityType.h"
#include "APIGetActivityResult.h"
#include "APIListActivitiesResult.h"

namespace ImmutablezkEVMAPI
{

/* Get a single activity by ID
 *
 * Get a single activity by ID
*/
class IMMUTABLEZKEVMAPI_API APIActivitiesApi::GetActivityRequest : public Request
{
public:
    virtual ~GetActivityRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* The id of activity */
	FGuid ActivityId;
};

class IMMUTABLEZKEVMAPI_API APIActivitiesApi::GetActivityResponse : public Response
{
public:
    virtual ~GetActivityResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIGetActivityResult Content;
};

/* List all activities
 *
 * List all activities
*/
class IMMUTABLEZKEVMAPI_API APIActivitiesApi::ListActivitiesRequest : public Request
{
public:
    virtual ~ListActivitiesRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* The contract address of NFT or ERC20 Token */
	TOptional<FString> ContractAddress;
	/* An `uint256` token id as string */
	TOptional<FString> TokenId;
	/* The account address activity contains */
	TOptional<FString> AccountAddress;
	/* The activity type */
	TOptional<APIActivityType> ActivityType;
	/* The transaction hash of activity */
	TOptional<FString> TransactionHash;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
};

class IMMUTABLEZKEVMAPI_API APIActivitiesApi::ListActivitiesResponse : public Response
{
public:
    virtual ~ListActivitiesResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIListActivitiesResult Content;
};

/* List history of activities
 *
 * List activities sorted by updated_at timestamp ascending, useful for time based data replication
*/
class IMMUTABLEZKEVMAPI_API APIActivitiesApi::ListActivityHistoryRequest : public Request
{
public:
    virtual ~ListActivityHistoryRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* From indexed at including given date */
	FDateTime FromUpdatedAt;
	/* To indexed at including given date */
	TOptional<FDateTime> ToUpdatedAt;
	/* The contract address of the collection */
	TOptional<FString> ContractAddress;
	/* The activity type */
	TOptional<APIActivityType> ActivityType;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
};

class IMMUTABLEZKEVMAPI_API APIActivitiesApi::ListActivityHistoryResponse : public Response
{
public:
    virtual ~ListActivityHistoryResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIListActivitiesResult Content;
};

}
