/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"

namespace ImmutablezkEVMAPI
{

/*
 * APICancelledOrderStatus
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APICancelledOrderStatus : public Model
{
public:
    virtual ~APICancelledOrderStatus() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	enum class NameEnum
	{
		Cancelled,
  	};

	static FString EnumToString(const NameEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, NameEnum& EnumValue);
	/* The order status indicating a order is has been cancelled or about to be cancelled. */
	NameEnum Name;
	/* Whether the cancellation of the order is pending */
	bool Pending = false;
	enum class CancellationTypeEnum
	{
		OnChain,
		OffChain,
		Underfunded,
  	};

	static FString EnumToString(const CancellationTypeEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, CancellationTypeEnum& EnumValue);
	/* Whether the cancellation was done on-chain or off-chain or as a result of an underfunded account */
	CancellationTypeEnum CancellationType;
};

}
