/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIFee.h"
#include "APIItem.h"
#include "APIProtocolData.h"

namespace ImmutablezkEVMAPI
{

/*
 * APICreateListingRequestBody
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APICreateListingRequestBody : public Model
{
public:
    virtual ~APICreateListingRequestBody() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString AccountAddress;
	FString OrderHash;
	/* Buy item for listing should either be NATIVE or ERC20 item */
	TArray<APIItem> Buy;
	/* Buy fees should only include maker marketplace fees and should be no more than two entries as more entires will incur more gas. It is best practice to have this as few as possible. */
	TArray<APIFee> Fees;
	/* Time after which the Order is considered expired */
	FDateTime EndAt;
	APIProtocolData ProtocolData;
	/* A random value added to the create Order request */
	FString Salt;
	/* Sell item for listing should be an ERC721 item */
	TArray<APIItem> Sell;
	/* Digital signature generated by the user for the specific Order */
	FString Signature;
	/* Time after which Order is considered active */
	FDateTime StartAt;
};

}
