/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIAssetVerificationStatus.h"
#include "APIChain.h"
#include "APICollectionContractType.h"

namespace ImmutablezkEVMAPI
{

/*
 * APICollection
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APICollection : public Model
{
public:
    virtual ~APICollection() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	APIChain Chain;
	/* The name of the collection */
	TOptional<FString> Name;
	/* The symbol of contract */
	TOptional<FString> Symbol;
	APICollectionContractType ContractType;
	/* The address of the contract */
	FString ContractAddress;
	/* The description of collection */
	TOptional<FString> Description;
	/* The url of the collection image */
	TOptional<FString> Image;
	/* The url of external link */
	TOptional<FString> ExternalLink;
	/* The uri for the metadata of the collection */
	TOptional<FString> ContractUri;
	/* The metadata uri for nft */
	TOptional<FString> BaseUri;
	APIAssetVerificationStatus VerificationStatus;
	/* When the collection was first indexed */
	FDateTime IndexedAt;
	/* When the collection was last updated */
	FDateTime UpdatedAt;
	/* When the collection metadata was last synced */
	TOptional<FDateTime> MetadataSyncedAt;
};

}
