/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIFulfillmentData200ResponseResult.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIFulfillmentData200Response
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APIFulfillmentData200Response : public Model
{
public:
    virtual ~APIFulfillmentData200Response() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	APIFulfillmentData200ResponseResult Result;
};

}
