/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIActivity.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIGetActivityResult
 *
 * Single activity
 */
class IMMUTABLEZKEVMAPI_API APIGetActivityResult : public Model
{
public:
    virtual ~APIGetActivityResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	APIActivity Result;
};

}
