/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIActivity.h"
#include "APIPage.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIListActivitiesResult
 *
 * List activities response
 */
class IMMUTABLEZKEVMAPI_API APIListActivitiesResult : public Model
{
public:
    virtual ~APIListActivitiesResult() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* List of activities */
	TArray<APIActivity> Result;
	APIPage Page;
};

}
