/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APIMetadataSearchApi.h"

#include "APIAPIError400.h"
#include "APIAPIError401.h"
#include "APIAPIError403.h"
#include "APIAPIError404.h"
#include "APIAPIError429.h"
#include "APIAPIError500.h"
#include "APIListFiltersResult.h"
#include "APISearchNFTsResult.h"
#include "APISearchStacksResult.h"

namespace ImmutablezkEVMAPI
{

/* Get list of metadata attribute filters
 *
 * Get list of metadata filters
*/
class IMMUTABLEZKEVMAPI_API APIMetadataSearchApi::ListFiltersRequest : public Request
{
public:
    virtual ~ListFiltersRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* Contract addresses for collection */
	FString ContractAddress;
};

class IMMUTABLEZKEVMAPI_API APIMetadataSearchApi::ListFiltersResponse : public Response
{
public:
    virtual ~ListFiltersResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIListFiltersResult Content;
};

/* Search NFTs
 *
 * Search NFTs
*/
class IMMUTABLEZKEVMAPI_API APIMetadataSearchApi::SearchNFTsRequest : public Request
{
public:
    virtual ~SearchNFTsRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* List of contract addresses to filter by */
	TArray<FString> ContractAddress;
	/* Account address to filter by */
	TOptional<FString> AccountAddress;
	/* Filters NFTs that belong to any of these stacks */
	TOptional<TArray<FGuid>> StackId;
	/* Whether the listings should include only the owner created listings */
	TOptional<bool> OnlyIncludeOwnerListings;
	/* Number of results to return per page */
	TOptional<int32> PageSize;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
};

class IMMUTABLEZKEVMAPI_API APIMetadataSearchApi::SearchNFTsResponse : public Response
{
public:
    virtual ~SearchNFTsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APISearchNFTsResult Content;
};

/* Search NFT stacks
 *
 * Search NFT stacks
*/
class IMMUTABLEZKEVMAPI_API APIMetadataSearchApi::SearchStacksRequest : public Request
{
public:
    virtual ~SearchStacksRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* List of contract addresses to filter by */
	TArray<FString> ContractAddress;
	/* Account address to filter by */
	TOptional<FString> AccountAddress;
	/* Whether to the listings should include only the owner created listings */
	TOptional<bool> OnlyIncludeOwnerListings;
	/* Filters results to include only stacks that have a current active listing. False and 'null' return all unfiltered stacks. */
	TOptional<bool> OnlyIfHasActiveListings;
	/* JSON encoded traits to filter by. e.g. encodeURIComponent(JSON.stringify({\"rarity\": {\"values\": [\"common\", \"rare\"], \"condition\": \"eq\"}})) */
	TOptional<FString> Traits;
	/* Keyword to search NFT name and description. Alphanumeric characters only. */
	TOptional<FString> Keyword;
	/* Filters the active listings, bids, floor listing and top bid by the specified payment token, either the address of the payment token contract or 'NATIVE' */
	TOptional<FString> PaymentToken;
	enum class SortByEnum
	{
		CheapestFirst,
  	};

	static FString EnumToString(const SortByEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, SortByEnum& EnumValue);
	/* Sort results in a specific order */
	TOptional<SortByEnum> SortBy;
	/* Number of results to return per page */
	TOptional<int32> PageSize;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
};

class IMMUTABLEZKEVMAPI_API APIMetadataSearchApi::SearchStacksResponse : public Response
{
public:
    virtual ~SearchStacksResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APISearchStacksResult Content;
};

}
