/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "Misc/TVariant.h"

#include "APIBaseModel.h"

namespace ImmutablezkEVMAPI
{

/*
 * APINFTMetadataAttributeValue
 *
 * The metadata trait value
 */
class IMMUTABLEZKEVMAPI_API APINFTMetadataAttributeValue : public Model
{
public:
    virtual ~APINFTMetadataAttributeValue() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TVariant<FString, bool, double> OneOf;
};

}
