/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APINftOwnersApi.h"

#include "APIAPIError400.h"
#include "APIAPIError404.h"
#include "APIAPIError500.h"
#include "APIListCollectionOwnersResult.h"
#include "APIListNFTOwnersResult.h"

namespace ImmutablezkEVMAPI
{

/* List all NFT owners
 *
 * List all NFT owners on a chain
*/
class IMMUTABLEZKEVMAPI_API APINftOwnersApi::ListAllNFTOwnersRequest : public Request
{
public:
    virtual ~ListAllNFTOwnersRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The name of chain */
	FString ChainName;
	/* Datetime to use as the oldest updated timestamp */
	TOptional<FDateTime> FromUpdatedAt;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
};

class IMMUTABLEZKEVMAPI_API APINftOwnersApi::ListAllNFTOwnersResponse : public Response
{
public:
    virtual ~ListAllNFTOwnersResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIListNFTOwnersResult Content;
};

/* List NFT owners by token ID
 *
 * List NFT owners by token ID
*/
class IMMUTABLEZKEVMAPI_API APINftOwnersApi::ListNFTOwnersRequest : public Request
{
public:
    virtual ~ListNFTOwnersRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The address of contract */
	FString ContractAddress;
	/* An `uint256` token id as string */
	FString TokenId;
	/* The name of chain */
	FString ChainName;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
};

class IMMUTABLEZKEVMAPI_API APINftOwnersApi::ListNFTOwnersResponse : public Response
{
public:
    virtual ~ListNFTOwnersResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIListNFTOwnersResult Content;
};

/* List owners by contract address
 *
 * List owners by contract address
*/
class IMMUTABLEZKEVMAPI_API APINftOwnersApi::ListOwnersByContractAddressRequest : public Request
{
public:
    virtual ~ListOwnersByContractAddressRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The address of contract */
	FString ContractAddress;
	/* The name of chain */
	FString ChainName;
	/* List of account addresses to filter by */
	TOptional<TArray<FString>> AccountAddress;
	/* Datetime to use as the oldest updated timestamp */
	TOptional<FDateTime> FromUpdatedAt;
	/* Encoded page cursor to retrieve previous or next page. Use the value returned in the response. */
	TOptional<FString> PageCursor;
	/* Maximum number of items to return */
	TOptional<int32> PageSize;
};

class IMMUTABLEZKEVMAPI_API APINftOwnersApi::ListOwnersByContractAddressResponse : public Response
{
public:
    virtual ~ListOwnersByContractAddressResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    APIListCollectionOwnersResult Content;
};

}
