/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "Misc/TVariant.h"

#include "APIBaseModel.h"
#include "APIOperatorAllowlistStatusRequested.h"
#include "APIOperatorAllowlistStatusUpdated.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIOperatorAllowlistStatusDetails
 *
 * The operator allowlist status details
 */
class IMMUTABLEZKEVMAPI_API APIOperatorAllowlistStatusDetails : public Model
{
public:
    virtual ~APIOperatorAllowlistStatusDetails() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TVariant<APIOperatorAllowlistStatusRequested, APIOperatorAllowlistStatusUpdated> OneOf;
};

}
