/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"
#include "APICall.h"
#include "APISignCraftingRequestMultiCaller.h"

namespace ImmutablezkEVMAPI
{

/*
 * APISignCraftingRequest
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APISignCraftingRequest : public Model
{
public:
    virtual ~APISignCraftingRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	APISignCraftingRequestMultiCaller MultiCaller;
	/* The id of this request in the system that originates the crafting request, specified as a 32 byte hex string */
	FString ReferenceId;
	/* The calls to be signed */
	TArray<APICall> Calls;
	/* The expiration time of the request */
	FDateTime ExpiresAt;
};

}
