/**
 * Immutable zkEVM API
 * Immutable Multi Rollup API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "APIBaseModel.h"

namespace ImmutablezkEVMAPI
{

/*
 * APIUnfulfillableOrder
 *
 * 
 */
class IMMUTABLEZKEVMAPI_API APIUnfulfillableOrder : public Model
{
public:
    virtual ~APIUnfulfillableOrder() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* OrderID for the requested but unfulfillable order */
	FString OrderId;
	/* Token ID for the ERC721 or ERC1155 token when fulfilling a collection order */
	TOptional<FString> TokenId;
	/* Nullable string containing error reason if the signing is unsuccessful for the order */
	FString Reason;
};

}
