---
name: "Tag Release"

on:
  pull_request:
    types: [closed]

jobs:
  create-tag:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from ImmutableDataTypes.h
        id: extract_version
        run: |
          version=$(grep -oP '#define ENGINE_SDK_VERSION TEXT\("\K[0-9]+\.[0-9]+\.[0-9]+' Source/Immutable/Public/Immutable/ImmutableDataTypes.h)

          if [[ -z "$version" ]]; then
            echo "Error: Version not found in ImmutableDataTypes.h" >&2
            exit 1
          fi

          version=$(echo "$version" | tr -d '\r\n')
          
          echo "VERSION=${version}" >> "$GITHUB_ENV"

      - name: Check TS SDK version exists in index.js
        id: check_ts_sdk_version
        run: |
          version=$(grep -oP '"x-sdk-version":"ts-immutable-sdk-\K[0-9]+\.[0-9]+\.[0-9]+' ./Web/index.js | head -n 1)

          if [[ -z "$version" ]]; then
            echo "Error: TS SDK version not found in index.js" >&2
            exit 1
          fi

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: "v${{ env.VERSION }}"
          message: "Version ${{ env.VERSION }}"
          token: ${{ secrets.GITHUB_TOKEN }}
