---
name: "Update engine SDK version in ImmutableDataTypes.h"

on:
  workflow_dispatch:
    inputs:
      upgrade_type:
        type: choice
        description: Upgrade Type
        options:
          - patch
          - minor
          # - major
        required: true
        default: patch

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.UNREAL_IMMUTABLE_SDK_GITHUB_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check team membership
      id: check_team
      run: |
        ./.github/scripts/check_team_membership.sh "${{ github.actor }}" "${{ secrets.UNREAL_IMMUTABLE_SDK_GITHUB_TOKEN }}"
        # shellcheck disable=SC1090
        source "$GITHUB_ENV"
        echo "${{ github.actor }} is a member of the SDK team: $IS_MEMBER"
        if [[ "$IS_MEMBER" != "true" ]]; then
          echo "Not a member of the SDK team, skipping update"
          exit 1
        fi

    - name: Replace engine sdk version string
      id: replace_engine_sdk_version
      run: |
        FILE=./Source/Immutable/Public/Immutable/ImmutableDataTypes.h
        VERSION=${{ github.event.inputs.version }}
        UPGRADE_TYPE=${{ github.event.inputs.upgrade_type }}
        
        # Split version into components
        IFS='.' read -r major minor patch <<< "$VERSION"
    
        # Update version based on upgrade_type
        if [ "$UPGRADE_TYPE" == "patch" ]; then
          patch=$((patch + 1))  # Increment patch version
        elif [ "$UPGRADE_TYPE" == "minor" ]; then
          minor=$((minor + 1))  # Increment minor version and reset patch
          patch=0
        fi
    
        # Format the updated version
        UPDATED_VERSION="$major.$minor.$patch"
    
        # Replace the version string in the file
        sed -i -E "s/#define ENGINE_SDK_VERSION TEXT\(\"[0-9]+\.[0-9]+\.[0-9]+\"\)/#define ENGINE_SDK_VERSION TEXT(\"$UPDATED_VERSION\")/g" $FILE

    - uses: gr2m/create-or-update-pull-request-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "chore: update version"
        body: "Update version in ImmutableDataTypes.h"
        branch: "chore/update-version-${{ github.event.inputs.version }}"
        commit-message: "chore: update version"
        labels: release
